"""rename address

Revision ID: 807af582ba48
Revises: 35fb9d7033b0
Create Date: 2026-07-21 00:37:24.247379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807af582ba48'
down_revision = '35fb9d7033b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
